version: '3.3'

services:
  ### Workspace Utilities ##################################
  web:
    image: krutpong/apache-php7.2-fpm
    volumes:
    - "${APP_PATH}:/var/www/tool-dev/"
    - "${SITE_AVAILABLE}:/etc/apache2/sites-available/"
    depends_on:
    - mysql
    environment:
      ENVIRONMENT: docker
    tty: true
    ports:
    - "80:80"
    - "443:443"

  ### MySql ##################################
  mysql:
    image: krutpong/mysql8.0
    volumes:
    - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - "3306:3306"

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
